### ISSUE TITLE
Inconsistent reference to license for docs

### ISSUE THREAD

**Issue by swinslow** [moby/spdystream#70]
Hello,

The README.md and LICENSE.docs files are inconsistent about which license applies to the spdystream documentation.

The README.md file says that docs are:
"...licensed under the _Creative Commons Attribution 4.0 International License_ under the terms and conditions set forth in the file "**LICENSE.docs**". You may obtain a duplicate copy of the same license, titled **CC-BY-SA-4.0**, at _http://creativecommons.org/licenses/by/4.0/_."

The bolded items say that the docs license is CC-BY-SA-4.0, but the italicized items say that it is CC-BY-4.0 (which is a different license).

If the intent is for the docs license to be CC-BY-4.0, could the following changes be made?

1. The LICENSE.docs file should likely be replaced with the CC-BY-4.0 license text, available from https://creativecommons.org/licenses/by/4.0/legalcode.txt

2. The bolded reference above to **CC-BY-SA-4.0** in README.md should likely be changed to CC-BY-4.0.

Thank you!

**Comment by swinslow** [comment]
For a similar issue in docker/classicswarm, I note that it has now been corrected to refer to CC-BY-SA-4.0 in all cases (see [issue](https://github.com/docker/classicswarm/issues/2833), [pr](https://github.com/docker/classicswarm/pull/2984/files)).

Is it possible to apply the same changes here, so that the license statement will be consistent?

**Comment by dmcgowan** [comment]
There are no docs, feel free to open a PR which removes the license.docs and any reference in the Readme. Applying apache 2 to the whole codebase would be consistent with other projects.

**Comment by shubham1172** [comment]
I believe this can be closed by https://github.com/moby/spdystream/pull/81
