### ISSUE TITLE
module still declares it's name as github.com/moby/spdystream

### ISSUE THREAD

**Issue by tml-hh** [moby/spdystream#85]
error shows when trying to update dependencies:

`go get: github.com/docker/spdystream@v0.1.0 updating to
        github.com/docker/spdystream@v0.2.0: parsing go.mod:
        module declares its path as: github.com/moby/spdystream
                but was required as: github.com/docker/spdystream`

obviously, the declaration comes from [here](https://github.com/moby/spdystream/blob/master/go.mod#L1)

**Comment by dims** [comment]
`go get github.com/docker/spdystream@v0.1.0` does that work?

**Comment by thaJeztah** [comment]
Odd; does it really want a major version update? 🤔

Or are there still references somewhere to the old name in the codebase? (why would it look for the old name if you add the new name? Would think that it would just consider it to be a "new" dependency)

**Comment by david-becher** [comment]
Correct me if I am wrong, but in the public index https://index.golang.org/ the old repository is still there, might this be the actual problem? This renaming essentially breaks a go get build for me, because the application I am trying to go get (k9s) depends on this repo.

**Comment by thaJeztah** [comment]
> This renaming essentially breaks a go get build for me

What version do you use in your go.mod? v0.1.0 and before use the old name as module name https://github.com/moby/spdystream/blob/v0.1.0/go.mod#L1, whereas `v0.2.0` uses the new name https://github.com/moby/spdystream/blob/v0.2.0/go.mod#L1

**Comment by thaJeztah** [comment]
```
$ GO111MODULE=on go get github.com/docker/spdystream@v0.1.0
go: downloading github.com/docker/spdystream v0.1.0
$ GO111MODULE=on go get github.com/moby/spdystream@v0.2.0
go: downloading github.com/moby/spdystream v0.2.0
```

**Comment by david-becher** [comment]
I did not use anything, I just wanted to install k9s (https://github.com/derailed/k9s):

```
GO111MODULE=on go get -u github.com/derailed/k9s
```

but it fails with

```
go get: github.com/docker/spdystream@v0.0.0-20160310174837-449fdfce4d96 updating to
	github.com/docker/spdystream@v0.2.0: parsing go.mod:
	module declares its path as: github.com/moby/spdystream
	        but was required as: github.com/docker/spdystream
```

 Do you know, how I would fix this? Does k9s have to fix this? I even can't build older versions of k9s.

**Comment by david-becher** [comment]
I think github.com/docker/spdystream is in some of the dependencies of k9s, but no matter what, I think the renaming broke some go get commands in certain situations.

Do you can help me understand, why the renaming breaks building k9s with go get? Unfortunately, I am not as experienced in go's handling of modules to understand what might be the actual underlying issue here.

**Comment by thaJeztah** [comment]
> Do you can help me understand, why the renaming breaks building k9s with go get?

Not exactly sure, but possibly there's a dependency that either doesn't use go modules yet (in which case `go get` will get "latest").

Probable fix for that would be for https://github.com/derailed/k9s to specify the version in their `go.mod` (as "indirect")

```go
require (
	...
	github.com/derailed/tview v0.4.9
	github.com/docker/spdystream v0.1.0
	github.com/drone/envsubst v1.0.2 // indirect
	...
```
```

**Comment by thaJeztah** [comment]
oh, actually; I see you use the `-u` option on `go get`. That's probably the culprit here;

```
go help get

...
The -u flag instructs get to use the network to update the named packages
*and their dependencies*. By default, get uses the network to check out
missing packages but does not use it to look for updates to existing packages.
...
```

Using `-u` will update dependency modules (which will pick newer versions if found).  

Running without `-u`, it works;

```console
$ GO111MODULE=on go get github.com/derailed/k9s
...
go: downloading github.com/derailed/k9s v0.24.2
go: github.com/derailed/k9s upgrade => v0.24.2
go: downloading k8s.io/client-go v0.18.8
...
go: downloading github.com/docker/spdystream v0.0.0-20160310174837-449fdfce4d96
...


$ k9s --help
K9s is a CLI to view and manage your Kubernetes clusters.
...
```

**Comment by david-becher** [comment]
Gotcha. Thats great! Thank you for your help! :)

**Comment by thaJeztah** [comment]
You're welcome!

FWIW, I somewhat consider it a bug that `go get` is suggesting version v0.2, whereas that module doesn't exist (it could expect that if it would use `GOPROXY=direct`, but when using the default proxy, I'd expect it to not suggest `v0.2` for the old name. pkg.go.dev looks to do it correct, and only shows `v0.1.0` for the old location; https://pkg.go.dev/github.com/docker/spdystream

<img width="435" alt="Screenshot 2021-02-18 at 17 23 28" src="https://user-images.githubusercontent.com/1804568/108388022-7f8d3000-720e-11eb-9a4e-eb6b123cfd98.png">

and v0.2.0 only for the new version; https://pkg.go.dev/github.com/moby/spdystream

<img width="449" alt="Screenshot 2021-02-18 at 17 23 40" src="https://user-images.githubusercontent.com/1804568/108388026-80be5d00-720e-11eb-82f7-614fc3dc1bea.png">

**Comment by thaJeztah** [comment]
Thanks! Yes, I'm not sure there's anything more we can for for this, so let me go ahead and close.

The discussion on this thread could help others find a solution for their specific situation though (and feel free to continue the conversation)

**Comment by jayunit100** [comment]
does this mean we need to set `buildvcs=false` ?

**Comment by thaJeztah** [comment]
@jayunit100 what's the problem you're running into? If you're using this module as a dependency;

- use `github.com/docker/spdystream v0.1.0` if something uses the old name
- but if it's used as import in your own project, then update the imports and use `github.com/moby/spdystream v0.2.0` (or for anything > v0.2.0

**Comment by jayunit100** [comment]
I found that I needed that flag to build sonobuoy ....

**Comment by thaJeztah** [comment]
Do you have steps to reproduce? I just tried, but it seems to work at least when using `go install`;

```bash
go install github.com/vmware-tanzu/sonobuoy@latest
go: downloading github.com/vmware-tanzu/sonobuoy v0.56.13
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/sirupsen/logrus v1.4.2
go: downloading github.com/spf13/cobra v0.0.5
go: downloading github.com/spf13/pflag v1.0.5
go: downloading golang.org/x/sync v0.0.0-20201020160332-67f06af15bc9
go: downloading golang.org/x/text v0.3.8
go: downloading gopkg.in/yaml.v2 v2.4.0
go: downloading k8s.io/api v0.21.3
go: downloading k8s.io/apimachinery v0.21.3
go: downloading k8s.io/client-go v0.21.3
go: downloading k8s.io/klog v1.0.0
go: downloading golang.org/x/sys v0.0.0-20220728004956-3c1f35247d10
go: downloading github.com/cpuguy83/go-md2man v1.0.10
go: downloading github.com/briandowns/spinner v1.6.1
go: downloading github.com/hashicorp/go-version v1.2.0
go: downloading golang.org/x/term v0.0.0-20210927222741-03fcf44c2211
go: downloading sigs.k8s.io/yaml v1.2.0
go: downloading gopkg.in/yaml.v3 v3.0.0-20200605160147-a5ece683394c
go: downloading github.com/satori/go.uuid v1.2.1-0.20181028125025-b2ce2384e17b
go: downloading github.com/rifflock/lfshook v0.0.0-20180920164130-b9218ef580f5
go: downloading github.com/gorilla/mux v1.7.3
go: downloading github.com/sethgrid/pester v0.0.0-20190127155807-68a33a018ad0
go: downloading github.com/spf13/viper v1.4.0
go: downloading github.com/gogo/protobuf v1.3.2
go: downloading github.com/google/gofuzz v1.1.0
go: downloading k8s.io/klog/v2 v2.8.0
go: downloading sigs.k8s.io/structured-merge-diff/v4 v4.1.2
go: downloading github.com/golang/protobuf v1.4.3
go: downloading github.com/googleapis/gnostic v0.4.1
go: downloading golang.org/x/net v0.0.0-20220906165146-f3363e06e74c
go: downloading github.com/imdario/mergo v0.3.7
go: downloading github.com/russross/blackfriday v1.5.2
go: downloading github.com/fatih/color v1.7.0
go: downloading k8s.io/utils v0.0.0-20201110183641-67b214c5f920
go: downloading github.com/google/go-cmp v0.5.4
go: downloading github.com/json-iterator/go v1.1.10
go: downloading github.com/modern-go/reflect2 v1.0.2
go: downloading github.com/fsnotify/fsnotify v1.4.7
go: downloading github.com/hashicorp/hcl v1.0.0
go: downloading github.com/magiconair/properties v1.8.1
go: downloading github.com/mitchellh/mapstructure v1.1.2
go: downloading github.com/pelletier/go-toml v1.4.0
go: downloading github.com/spf13/afero v1.2.2
go: downloading github.com/spf13/cast v1.3.0
go: downloading github.com/spf13/jwalterweatherman v1.1.0
go: downloading gopkg.in/inf.v0 v0.9.1
go: downloading github.com/go-logr/logr v0.4.0
go: downloading google.golang.org/protobuf v1.25.0
go: downloading golang.org/x/time v0.0.0-20210220033141-f8bda1e9f3ba
go: downloading github.com/Azure/go-autorest/autorest v0.11.12
go: downloading github.com/Azure/go-autorest v14.2.0+incompatible
go: downloading github.com/Azure/go-autorest/autorest/adal v0.9.5
go: downloading golang.org/x/oauth2 v0.0.0-20200107190931-bf48bf16ab8d
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading github.com/mattn/go-colorable v0.1.2
go: downloading github.com/mattn/go-isatty v0.0.8
go: downloading github.com/hashicorp/golang-lru v0.5.1
go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: downloading github.com/Azure/go-autorest/logger v0.2.0
go: downloading github.com/Azure/go-autorest/tracing v0.6.0
go: downloading github.com/Azure/go-autorest/autorest/date v0.3.0
go: downloading github.com/form3tech-oss/jwt-go v3.2.2+incompatible
go: downloading golang.org/x/crypto v0.0.0-20220411220226-7b82a4e95df4
go: downloading cloud.google.com/go v0.54.0
go: downloading github.com/moby/spdystream v0.2.0


sonobuoy --help
Sonobuoy is a Kubernetes component that generates reports on cluster conformance, configuration, and more

Usage:
  sonobuoy [flags]
  sonobuoy [command]

Available Commands:
  delete      Deletes Kubernetes resources that were generated by a Sonobuoy run
  e2e         Generates a list of all tests and tags in that tests
  gen         Generates a sonobuoy manifest for submission via kubectl
  get         Fetches Sonobuoy resources of a specified type
  help        Help about any command
  images      Manage images used in a plugin to facilitate running them in airgapped (or similar) environments. Supported plugins are: 'e2e'
  logs        Dumps the logs of the currently running Sonobuoy containers for diagnostics
  modes       Display the various modes in which to run the e2e plugin
  plugin      Manage your installed plugins
  query       Runs queries against your cluster in order to aid in debugging.
  results     Inspect plugin results.
  retrieve    Retrieves the results of a sonobuoy run to a specified path
  run         Starts a Sonobuoy run by launching the Sonobuoy aggregator and plugin pods.
  status      Gets a summarized status of a sonobuoy run
  version     Print sonobuoy version
  wait        Waits on the Sonobuoy run in the targeted namespace.

Flags:
  -h, --help          help for sonobuoy
      --level level   Log level. One of {panic, fatal, error, warn, info, debug, trace} (default info)

Use "sonobuoy [command] --help" for more information about a command.
```


Their `go.mod` also references it with the correct version and name; https://github.com/vmware-tanzu/sonobuoy/blob/9e95f1a67c33a1699f2d4e22d2836d0fca13fd08/go.mod#L61

```
	github.com/moby/spdystream v0.2.0 // indirect
```
