### ISSUE TITLE
What's the purpose of the 10 minute wait?

### ISSUE THREAD

**Issue by ryshoooo** [moby/spdystream#92]
In the microservice I'm building, I've experienced a memory leak using the Kubernetes client-go package, which I traced back to https://github.com/moby/spdystream/blob/master/connection.go#L733.

The memory leak is really well documented in https://github.com/kubernetes/kubernetes/issues/105830.

Essentially what happens is that running the stream executors with in-cluster kubeconfig context leads to many broken pipes, which leads to the waiting time of 10 minutes before the shutdown goroutine ends. This waiting time keeps the data in memory alive. Not a big deal if it's a small number of broken pipes, but in my case the number is rising very quickly and easily can reach 2-3 GB of allocated memory within the 10-minute hold, thus considering it a memory leak of high significance (essentially a system-service pod is taking memory that the users of the cluster can't use).

The fix for this is that I replaced the waiting time from 10 minutes to 10 milliseconds instead, and the memory leak is "gone"(not truly gone, just very low and GCed quickly). However, I wonder what are the repercussions of changing https://github.com/moby/spdystream/blob/master/connection.go#L733 to milliseconds? Also, what is the point of waiting here in the first place?

**Comment by 134130** [comment]
Getting same problem.
@ryshoooo How did you solved this problem? did you forked this and customized?

**Comment by liggitt** [comment]
I opened a fix for this in https://github.com/moby/spdystream/pull/99

If the error is not handled / consumed from the shutdownChan, there's still a 10 minute timeout, but if the error is consumed (as expected), there is no background goroutine spawned / leaking

**Comment by aojea** [comment]
I think this can be closed now

**Comment by dims** [comment]
thanks @aojea @liggitt

**Comment by liggitt** [comment]
https://github.com/moby/spdystream/pull/99 only avoided the 10 minute wait when the close error is handled / consumed... I think there's more to do to improve the case where it is not explicitly handled / consumed ... 10 minutes is a long time to leave the shutdown call hung, I think

**Comment by liggitt** [comment]
opened a follow-up in https://github.com/moby/spdystream/pull/101 to shorten the timeout for the unhandled error case
